# Generated by Django 5.2.4 on 2025-11-27 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultContentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('category', models.CharField(choices=[('pornography', 'Pornography'), ('nudity', 'Nudity'), ('adult_dating', 'Adult Dating'), ('illegal_content', 'Illegal Content'), ('malware', 'Malware/Phishing'), ('spam', 'Spam')], default='pornography', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, help_text='Why this domain is blocked')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adult Content Domain',
                'verbose_name_plural': 'Adult Content Domains',
                'ordering': ['-added_at'],
            },
        ),
    ]
